"""MP3 file conversion helpers.

Convert MP3 audio files into the project's MusicSignal container.
Uses librosa for loading MP3 files.
"""

import numpy as np
from data_classes.musicsignal import MusicSignal, MusicMetadata

try:
    import librosa
except ImportError:
    librosa = None

try:
    from scipy.io import wavfile
except ImportError:
    wavfile = None


# pylint: disable=too-many-arguments, too-many-positional-arguments
def convert_mp3(file_path, channels=None, author=None, music_type=None,
                length=None, source=None):
    """
    Convert MP3 file to MusicSignal object.

    Requires librosa: pip install librosa

    Args:
        file_path: Path to MP3 file
        channels: List of channel names (optional, auto-generated by default)
        author: Author/artist name
        music_type: Type of music (e.g., "Electronic", "Classical", etc.)
        length: Duration in seconds (auto-calculated if not provided)
        source: Source/dataset name

    Returns:
        MusicSignal object
    """
    if librosa is None:
        raise ImportError("librosa is required. Install with: pip install librosa")

    # Load audio file using librosa
    # librosa.load returns (y, sr) where y is the audio time series and sr is the sampling rate
    # mono=False to keep stereo information if available
    try:
        y, fs = librosa.load(file_path, sr=None, mono=False)
    except Exception as e:
        raise RuntimeError(f"Failed to load MP3 file '{file_path}': {e}")

    # Ensure we have 2D array (n_samples, n_channels)
    if len(y.shape) == 1:
        # Mono audio - reshape to (n_samples, 1)
        y = y.reshape(-1, 1)
        n_channels = 1
    else:
        # Stereo or multi-channel - transpose from (n_channels, n_samples) to (n_samples, n_channels)
        y = y.T
        n_channels = y.shape[1]

    # Convert to float32
    audio_array = y.astype(np.float32)

    n_samples = audio_array.shape[0]
    time = np.linspace(0, n_samples / fs, n_samples, dtype=np.float64)

    if channels is None:
        if n_channels == 1:
            channels = ["Mono"]
        elif n_channels == 2:
            channels = ["Left", "Right"]
        else:
            channels = [f"Ch{i + 1}" for i in range(n_channels)]

    if length is None:
        length = n_samples / fs

    metadata = MusicMetadata(
        author=author or "unknown",
        music_type=music_type or "unknown",
        length=float(length),
        source=source or str(file_path),
        extra={
            'source_file': str(file_path),
            'original_format': 'MP3',
            'n_channels': n_channels,
            'n_samples': n_samples,
        }
    )

    return MusicSignal(
        values=audio_array,
        fs=int(fs),
        channels=channels,
        time=time,
        metadata=metadata,
    )


def music_signal_to_mp3(music_signal, output_path: str) -> None:
    """
    Convert MusicSignal to MP3 file.

    Uses scipy.io.wavfile to create a temporary WAV, then converts to MP3
    using pydub if available, otherwise saves as WAV.

    Args:
        music_signal: MusicSignal object
        output_path: Output file path (MP3 or WAV)
    """
    if wavfile is None:
        raise ImportError("scipy is required. Install with: pip install scipy")

    # Prepare audio data - mix to mono if multi-channel
    audio_data = music_signal.values.copy()

    if len(audio_data.shape) > 1 and audio_data.shape[1] > 1:
        # Mix channels to mono
        audio_data = np.mean(audio_data, axis=1)
    elif len(audio_data.shape) > 1:
        audio_data = audio_data.flatten()

    # Normalize and convert to int16 for WAV format
    max_val = np.max(np.abs(audio_data))
    if max_val > 0:
        audio_data = audio_data / max_val

    # Scale to int16 range
    audio_data = (audio_data * 32767).astype(np.int16)

    if output_path.lower().endswith('.mp3'):
        # Try to use pydub to convert to MP3
        try:
            import tempfile
            from pydub import AudioSegment

            with tempfile.NamedTemporaryFile(suffix='.wav', delete=False) as tmp_wav:
                wavfile.write(tmp_wav.name, int(music_signal.fs), audio_data)
                audio = AudioSegment.from_wav(tmp_wav.name)
                audio.export(output_path, format="mp3", bitrate="192k")
                print(f"Successfully saved MP3 to: {output_path}")
        except ImportError:
            # Fallback to WAV if pydub is not available
            wav_path = output_path.replace('.mp3', '.wav')
            wavfile.write(wav_path, int(music_signal.fs), audio_data)
            print(f"pydub not available. Saved WAV to: {wav_path}")
    else:
        # Save as WAV
        wavfile.write(output_path, int(music_signal.fs), audio_data)
        print(f"Successfully saved WAV to: {output_path}")

